// @ts-ignore Generated by the OpenNext Cloudflare build.
import generatedWorker, { DOQueueHandler, DOShardedTagCache } from './.open-next/worker.js';

const DEFAULT_SITE_URL = 'https://fmoviesz.cyou';
const CRON_PATHS = ['/api/cron/index-new', '/api/cron/generate-blog'];

async function callCron(path: string, env: any, ctx: any) {
  const siteUrl = env.NEXT_PUBLIC_SITE_URL || process.env.NEXT_PUBLIC_SITE_URL || DEFAULT_SITE_URL;
  const cronSecret = env.CRON_SECRET || process.env.CRON_SECRET || process.env.JWT_SECRET;
  const headers = cronSecret ? { authorization: `Bearer ${cronSecret}` } : undefined;
  const request = new Request(new URL(path, siteUrl).toString(), {
    method: 'GET',
    headers,
  });

  const response = await generatedWorker.fetch(request, env, ctx);
  if (!response.ok) {
    const body = await response.text().catch(() => '');
    throw new Error(`Cloudflare cron failed for ${path}: ${response.status} ${body}`);
  }
}

export default {
  fetch: generatedWorker.fetch,
  async scheduled(_controller: any, env: any, ctx: any) {
    ctx.waitUntil(
      Promise.all(CRON_PATHS.map((path) => callCron(path, env, ctx)))
    );
  },
};

export { DOQueueHandler, DOShardedTagCache };